### ISSUE TITLE
help file?

### ISSUE THREAD

**Issue by lutsifer** [joselara/laravel-rets-client#1]
Hey man, yesterday i found your work here...I tried to use it but... a little help how to install it like what to write in aliases and providers will be great benefit of for me :)

**Comment by lutsifer** [comment]
Actually I put 
'Lara\Rets\RetsServiceProvider',

inside app.php and and after filling login credentials inside config  it looks like it start work (I am unable to get results yet but at least is not trowing errors..)

**Comment by lutsifer** [comment]
It doesnt matter how I play with options I always get this error here..

< HTTP/1.1 200 OK
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
* Replaced cookie JSESSIONID="E8BA03F173E2FCBA2BA31D83AEBA1DBF" for domain rets.mfrmls.com, path /contact, expire 0
< Set-Cookie: JSESSIONID=E8BA03F173E2FCBA2BA31D83AEBA1DBF; Path=/contact
< MIME-Version: 1.0
< Cache-Control: private
< RETS-Version: RETS/1.7.2
< Content-Type: text/xml
< Content-Length: 59
< Date: Tue, 03 Feb 2015 21:36:25 GMT
< 
* Connection #63 to host rets.mfrmls.com left intact
<RETS ReplyCode="20207" ReplyText="Unauthorized Query" />

**Comment by lutsifer** [comment]
Great, all problems are solved, yet is good to write how people to register provider...
Thank you for the code!

**Comment by joselara** [comment]
Glad you figured it out.

**Comment by stevesmename** [comment]
Was code removed? I'm getting Unauthorized Query responses for MFRMLS and trying to diagnose my issue.

**Comment by joselara** [comment]
I am not maintaining this codebase anymore, please checkout: https://github.com/troydavisson/PHRETS

Jose
